# Generated by Django 3.2.16 on 2023-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=255),
            preserve_default=False,
        ),
    ]
